#cloud-config

package_update: true
package_upgrade: true






 
runcmd:

    - git clone https://github.com/akilawi/naca_airfoil.git
    - mv naca_airfoil /home/ubuntu/
    - mkdir /home/ubuntu/naca_airfoil/geo
    - mkdir /home/ubuntu/naca_airfoil/msh
    - mkdir /home/ubuntu/naca_airfoil/xml


    # change permissions of the airfoil files
    - chmod -R 777 /home/ubuntu/naca_airfoil
    #- [chown, -R, ubuntu, project]

    #- export LC_ALL=C
    - cd /home/ubuntu/naca_airfoil
    - instanceip=$(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')
    - export BROKER_IP=$instanceip
    #Set password to rabbithq
    - rabbitmqctl add_user group5 group5
    - rabbitmqctl add_vhost naca
    - rabbitmqctl set_permissions -p naca group5 ".*" ".*" ".*"
    - celery -A tasks worker --loglevel=info